FROM golang:1.24-alpine AS build

WORKDIR /app

COPY backend/go.mod backend/go.sum ./
COPY backend/vendor ./vendor
COPY backend/cmd ./cmd
COPY backend/internal ./internal

RUN go build -mod=vendor -o server ./cmd/server

FROM alpine:3.20

WORKDIR /app

COPY --from=build /app/server ./server

EXPOSE 8081

CMD ["./server"]
