FROM golang:1.22-alpine AS build

WORKDIR /app

COPY backend/go.mod ./
COPY backend/cmd ./cmd
COPY backend/internal ./internal

RUN go mod tidy && go build -o server ./cmd/server

FROM alpine:3.20

WORKDIR /app

COPY --from=build /app/server ./server

EXPOSE 8081

CMD ["./server"]
